dogfood: Restore VPP token association to teams (#23114)
To fix
https://github.com/fleetdm/fleet/actions/runs/11468989615/job/31915263035#step:7:174

```
Error: applying app store apps for team: "🔳🏢 Company-owned iPads": POST /api/latest/fleet/software/app_store_apps/batch received status 422 Unprocessable Entity: could not retrieve vpp token: No available VPP Token
```

https://github.com/fleetdm/fleet/pull/22326 fixed so that GitOps removes
associations if they are not set (GitOps mode of operation where stuff
that's not set is removed), thus we now need to define it.