Update gitops exceptions message for 4.84 (#43471)
<!-- Add the related story/sub-task/bug number, like Resolves #123, or
remove if NA -->
**Related issue:** Resolves #43461 

> ### Note this is a PR directly to 4.84 as the message contains
4.84-specific language that will be adjusted for 4.85 (all errors will
look more like the "software" one, not mentioning defaults etc.)

# Checklist for submitter

If some of the following don't apply, delete the relevant line.

- [ ] Changes file added for user-visible changes in `changes/`,
`orbit/changes/` or `ee/fleetd-chrome/changes`.
See [Changes
files](https://github.com/fleetdm/fleet/blob/main/docs/Contributing/guides/committing-changes.md#changes-files)
for more information.
n/a, unreleased

## Testing

- [X] Added/updated automated tests
- [X] QA'd all new/changed functionality manually

Did `~/Development/fleet$ ./build/fleetctl gitops -f
/tmp/test-ex-msg/fleets/💻-workstations.yml` with various settings:

**Labels:**
```
Error: Starting in 4.84, labels management in GitOps is turned off by default.  Either remove `labels:` from your GitOps file or disable the exception in the UI: https://localhost:8080/settings/integrations/change-management
```

**Secrets**
```
Error: Starting in 4.84, secrets management in GitOps is turned off by default.  Either remove `secrets:` from your GitOps file or disable the exception in the UI: https://localhost:8080/settings/integrations/change-management
```

**Software**
```
Error: Software is excepted from GitOps management. Either remove `software:` from your GitOps file or disable the exception in the UI: https://localhost:8080/settings/integrations/change-management
```


For unreleased bug fixes in a release candidate, one of:

- [X] Confirmed that the fix is not expected to adversely impact load
test results