Allow concurrent `make lint-go` executions (#44724)
Usually I type `make lint-go` > enter, and then I go to do other stuff
and when I come back to the terminal I see this error (possibly because
VS Code is also running it?):
```
$ make lint-go
golangci-lint run --timeout 15m
Error: parallel golangci-lint is running
The command is terminated due to an error: parallel golangci-lint is running
```

Flag `--allow-serial-runners` is useful for this scenario:
```
--allow-serial-runners  Allow multiple golangci-lint instances running, but serialize them around a lock.
```

<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->

## Summary by CodeRabbit

* **Chores**
* Updated internal build configuration for linting tools to enhance
performance during development and testing cycles.

<!-- end of auto-generated comment: release notes by coderabbit.ai -->