Added Apple Root Cert for gdmf request. (#27483)
I manually verified this fix by running the new
`github.com/fleetdm/fleet/v4/server/mdm/apple/gdmf/integrationtest` test
with and without the fix on a cloud Ubuntu server.

Without fix:
```
=== RUN   TestGetAssetMetadata
    gdmf_test.go:14:
        	Error Trace:	/root/fleet/server/mdm/apple/gdmf/integrationtest/gdmf_test.go:14
        	Error:      	Received unexpected error:
        	            	retrieving asset metadata: Get "https://gdmf.apple.com/v2/pmv": tls: failed to verify certificate: x509: certificate signed by unknown authority
        	Test:       	TestGetAssetMetadata
--- FAIL: TestGetAssetMetadata (3.53s)
FAIL
FAIL	github.com/fleetdm/fleet/v4/server/mdm/apple/gdmf/integrationtest	3.542s
FAIL
```

With fix:
```
=== RUN   TestGetAssetMetadata
--- PASS: TestGetAssetMetadata (0.39s)
PASS
ok  	github.com/fleetdm/fleet/v4/server/mdm/apple/gdmf/integrationtest	0.397s
```

# Checklist for submitter

- [x] Changes file added for user-visible changes in `changes/`,
`orbit/changes/` or `ee/fleetd-chrome/changes`.
- [x] Added/updated automated tests
- [x] Manual QA for all new/changed functionality